import { Option } from "../datatypes/Option";
import { HTMLFormFieldElement, HTMLFormFieldValue, HTMLFormFieldTag, FormFieldSelectorExpression } from "../datatypes/base";
export declare function isFormElement(x: unknown): x is HTMLFormElement;
export declare function isInputFieldElement(x: unknown): x is HTMLInputElement;
export declare function isTextareaFieldElement(x: unknown): x is HTMLTextAreaElement;
export declare function isSelectFieldElement(x: unknown): x is HTMLSelectElement;
export declare function isFormFieldElement(x: unknown): x is HTMLFormFieldElement;
export declare function $getform(x: unknown): Option<HTMLFormElement>;
export declare function $getfield(x: unknown, y?: unknown): Option<HTMLFormFieldElement>;
export declare function localtimestamp(datestring: string, timeZone?: string): number;
export declare function getInputFieldValue($target: unknown): Option<HTMLFormFieldValue>;
export declare function getSelectFieldValue($target: unknown): Option<HTMLFormFieldValue>;
export declare function getTextareaFieldValue($target: unknown): Option<HTMLFormFieldValue>;
export declare function getFormFieldValue($target: unknown): Option<HTMLFormFieldValue>;
export declare function getFormFieldModifiedState($target: unknown): boolean;
export declare function isFormFieldElementActive($target: unknown): boolean;
export declare function isFormFieldValue(x: unknown): x is HTMLFormFieldValue;
export declare function isFormFieldInternalTag(x: unknown): x is HTMLFormFieldTag;
export declare function isFormFieldSelectorExpression(x: unknown): x is FormFieldSelectorExpression;
